base_kwargs:
  name: Test2
  save_dir: /mnt/scratch/Saved_Networks/METNet/
  device: gpu
loss_kwargs:
  reg_loss_fn: huber
  dst_loss_fn: engmmd
  dst_weight: 0
dense_kwargs:
  act_h: silu
  num_blocks: 3
  hddn_dim: 64
  nrm: layer